version: '3.9'

services:
  es01:
    container_name: es01
    image: platinaa777/chat-roulette:elastic01
    volumes:
      - esdata01:/usr/share/elastisearch/data
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: [ chat-net ]
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.db==yes"

  kibana:
    depends_on:
      - es01
    container_name: kibana
    image: platinaa777/chat-roulette:kibana01
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks: [ chat-net ]
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.db==yes"

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  chat-net:
    external: true
