version: '3.9'

volumes:
  rabbitdata:
    driver: local

networks:
  chat-net:
    external: true

services:
  rabbit_mq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MESSAGE_BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${MESSAGE_BROKER_PASSWORD}
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      - chat-net