version: '3.9'

networks:
  chat-app:
    driver: bridge

services:
  postgres_db:
    image: postgres
    container_name: users-profile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: denis123
      POSTGRES_DB: users_profile_db
    networks: [ chat-app ]
    volumes:
      - profile_data:/var/lib/postgresql/data

volumes:
  profile_data:
