version: '3.9'

networks:
  chat-net:
    driver: bridge

services:
  postgres_db:
    image: postgres
    container_name: users-profile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: denis123
      POSTGRES_DB: users_profile_db
    networks: [ chat-net ]
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  postgres_db: