version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "3000:443"
      - "443:443"
    configs:
      - source: site07
        target: /etc/nginx/conf.d/default.conf
      - source: certs01
        target: /etc/ssl/your_domain.crt
      - source: key01
        target: /etc/ssl/your_domain.key
    networks: [ chat-net ]
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-certbot:/var/www/certbot
    deploy:
      placement:
        constraints:
          - "node.role==manager"

volumes:
  etc-letsencrypt:
  www-certbot:

networks:
  chat-net:
    external: true

configs:
  site07:
    external: true
  certs01:
    external: true
  key01:
    external: true
