version: '3.9'

services:
  auth_app:
    image: platinaa777/chat-roulette:auth12
    environment:
      Jwt__Key: ${AUTH_JWT_KEY}
      AuthDbConnection__AUTH_DB_USER: ${AUTH_DB_USER}
      AuthDbConnection__AUTH_DB_PASSWORD: ${AUTH_DB_PASS}
      AuthDbConnection__AUTH_DB_HOST: ${AUTH_DB_HOST}
      AuthDbConnection__AUTH_DB: ${AUTH_DB}
      AuthDbConnection__AUTH_DB_PORT: ${AUTH_DB_PORT}
      MessageBroker__UserName: ${MESSAGE_BROKER_USER}
      MessageBroker__Password: ${MESSAGE_BROKER_PASSWORD}
      OtlpExporter__Uri: ${OPEN_TELEMETRY_EXPORTER}
    networks: [ chat-net ]
    deploy:
      endpoint_mode: dnsrr
  
  db_auth_server:
    image: postgres
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    networks: [ chat-net ]
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - "node.hostname==worker01"
      endpoint_mode: dnsrr

  redis_cache_auth:
    image: redis
    volumes:
      - redis_data:/data
    networks: [ chat-net ]
    deploy:
      placement:
        constraints:
          - "node.hostname==worker01"
      endpoint_mode: dnsrr

volumes:
  auth_db_data:
  redis_data:

networks:
  chat-net:
    external: true
