version: '3.9'

services:
  profile_app:
    image: platinaa777/chat-roulette:profile02
    environment:
      Jwt__Key: ${AUTH_JWT_KEY}
      DatabaseOptions__ConnectionString: ${PROFILE_CONN_STRING}
      MessageBroker__UserName: ${MESSAGE_BROKER_USER}
      MessageBroker__Password: ${MESSAGE_BROKER_PASSWORD}
      OtlpExporter__Uri: ${OPEN_TELEMETRY_EXPORTER}
    networks: [ chat-net ]
  
  db_profile:
    image: postgres
    environment:
      POSTGRES_USER: ${PROFILE_DB_USER}
      POSTGRES_PASSWORD: ${PROFILE_DB_PASS}
      POSTGRES_DB: ${PROFILE_DB}
    networks: [ chat-net ]
    volumes:
      - profile_db_data:/var/lib/postgresql/data
    ports:
      - "8084:5432"
    deploy:
      placement:
        constraints:
          - "node.hostname==worker01"
  
  redis_cache_profile:
    image: redis
    ports:
      - "8085:6379"
    volumes:
      - redis_data_profile:/data
    networks: [ chat-net ]
    deploy:
      placement:
        constraints:
          - "node.hostname==worker01"

volumes:
  profile_db_data:
  redis_data_profile:

networks:
  chat-net:
    external: true