version: '3.9'

services:
  profile_migrations:
    image: platinaa777/chat-roulette:profile-migrations02
    environment:
      Jwt__Key: ${AUTH_JWT_KEY}
      DatabaseOptions__ConnectionString: ${PROFILE_CONN_STRING}
      MessageBroker__UserName: ${MESSAGE_BROKER_USER}
      MessageBroker__Password: ${MESSAGE_BROKER_PASSWORD}
      OtlpExporter__Uri: ${OPEN_TELEMETRY_EXPORTER}
    networks: [ chat-net ]

volumes:
  profile_db_data:

networks:
  chat-net:
    external: true